"""add_banner_key_to_users

Revision ID: 3a9fb920f050
Revises: 17d6b1f60610
Create Date: 2026-08-02 12:18:45.694795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9fb920f050'
down_revision: Union[str, Sequence[str], None] = '17d6b1f60610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banner_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banner_key')
    # ### end Alembic commands ###
