"""Add the boxes table and the relationship in the shelves table

Revision ID: 2770e5b277b9
Revises: cb87d1b7f360
Create Date: 2026-03-04 09:49:44.861780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2770e5b277b9'
down_revision: Union[str, Sequence[str], None] = 'cb87d1b7f360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boxes',
    sa.Column('shelf_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'RUB', 'EUR', 'GBP', 'CNY', 'JPY', 'KZT', 'BYN', 'TRY', name='currencyenum'), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'GOLDEN', 'DEV', name='boxrarity'), nullable=False),
    sa.Column('is_sealed', sa.Enum('SEALED', 'NOT_SEALED', name='sealingenum'), nullable=False),
    sa.Column('is_public', sa.Enum('PUBLIC', 'PRIVATE', 'LIMITED', 'BY_THE_LINK', name='visibilityenum'), nullable=False),
    sa.Column('is_verified', sa.Enum('VERIFIED', 'NOT_VERIFIED', 'ON_CHECKING', 'SCAM', name='verifyenum'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boxes')
    # ### end Alembic commands ###
