"""add_gifted_by_and_is_gift_public_to_box_instances

Revision ID: 17d6b1f60610
Revises: 9e088880806e
Create Date: 2026-08-02 12:06:24.972133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d6b1f60610'
down_revision: Union[str, Sequence[str], None] = '9e088880806e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box_instances', sa.Column('gifted_by_id', sa.UUID(), nullable=True))
    op.add_column('box_instances', sa.Column('is_gift_public', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_foreign_key(None, 'box_instances', 'users', ['gifted_by_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('uq_users_username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('uq_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint(None, 'box_instances', type_='foreignkey')
    op.drop_column('box_instances', 'is_gift_public')
    op.drop_column('box_instances', 'gifted_by_id')
    # ### end Alembic commands ###
